### ISSUE TITLE
Feature request: create tests folder if missing

### ISSUE THREAD

**Issue by jonom** [gordonbanderson/SilverStripeTestTools#1]
Hi Gordon, just playing with this module, looks pretty handy!

I noticed maketests errors if the tests folder doesn't exist, would be cool if the script created it if not available. I would add this myself but I'm not familiar with Ruby.

**Comment by gordonbanderson** [comment]
0119 my time, will fix tomorrow.  The mkdir command is here http://ruby-doc.org/core-2.2.0/Dir.html, as is exists?, to check if a file or directory exists.  Should only take 5 mins to fix when awake.

And technically this is not a module but just a script, Ruby is my language of choice when some language agnostic task needs done.

There are a few other edge cases where it generates broken code, and it should probably also conform to PSR-2 (brackets not compliant).

**Comment by jonom** [comment]
Thanks :)
